# gunakan base image dari Node js versi 20
FROM node:20

# set working directory di container
WORKDIR /app

# copy file project
COPY package*.json ./
COPY tsconfig.json ./
COPY prisma ./prisma
COPY src ./src

# install dependencies
RUN npm install

# build typescript ke javascript
RUN npm run build

# copy file .env
COPY .env .env

# jalankan perintah saat container start
CMD ["npm", "run", "start"]